# Settings for Travis

language: python
python:
  - '3.8'

branches:
  only:
    - main

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="settings.travis"

services:
  - postgresql

script:
  - python manage.py test