# Settings for Travis

language: python
python:
  - '3.8'

branches:
  only:
    - main

before_script:
  - pip install -r requirements.txt

env: DJANGO_SETTINGS_MODULE="pur_beurre.settings"

services:
  - postgresql

script:
  - ./manage.py test