# Generated by Django 3.2.6 on 2021-09-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aliment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnns_groups_1', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('nutriscore', models.CharField(max_length=1)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('aliments', models.ManyToManyField(related_name='favorites', to='search.Aliment')),
            ],
        ),
    ]
