# Generated by Django 3.2.6 on 2021-09-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_rename_product_aliment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aliment',
            name='url',
            field=models.URLField(),
        ),
    ]
