# Generated by Django 3.2.6 on 2021-09-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_alter_aliment_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category']},
        ),
        migrations.AlterField(
            model_name='aliment',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
