# Generated by Django 3.2.6 on 2021-09-22 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20210922_1243'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aliment',
            new_name='Product',
        ),
    ]
