# Generated by Django 3.2.6 on 2021-09-22 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_rename_aliment_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Aliment',
        ),
    ]
