# Generated by Django 3.2.6 on 2021-10-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='aliment',
            name='img_url',
            field=models.URLField(default=None),
        ),
    ]
